[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[build.nixpacksPlan.phases.build]
cmds = ["dotnet publish -c Release -o out"]

[deploy]
startCommand = "dotnet out/ITransitionTask3.dll --urls=http://0.0.0.0:$PORT"